# Worksheet 04

Name:  Jiang Cheng Liu
UID: U77948366

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

1. p: tweaks the distance function that you are working with, ex. p = 2 -> euclidean distance, p = 1 -> manhattan distance
2. d: how many dimensions to the space that we are working with

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Manhattan distance can not calculate diagonal points while euclidean can. 

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The distance between two points will approach 1. 

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No because it would violate the triangle distance. 

e) when would you use cosine similarity over the euclidan distance?

When you are more interested in the direction/order of the vectors rather than magnitude. This would be done for situations like text processing between two documents and the topic that they are discussing. 

f) what does the jaccard distance account for that the manhattan distance doesn't?

It accounts for the size of the intersection between points. 

#### Part 2

Consider the following two sentences:

In [20]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [21]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [22]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'Bob', 'Alice', 'my', 'is', 'name']
[1, 0, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [23]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [24]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['Claude', 'hello', 'Bob', 'hi', 'Alice', 'my', 'is', 'name']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [25]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 1, 0, 0, 1, 1, 1, 1]
[0, 1, 1, 0, 0, 1, 1, 1]
[1, 0, 0, 1, 0, 1, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [26]:
def minkowski(x, y, p):
    if len(x) != len(y):
        raise RuntimeError("x and y must be the same direction")
    return sum([abs(x[i] - y[i])**p for i in range(len(x))])**(1/p)
print(minkowski([0,0], [1,1], 1))
    

2.0


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [27]:
s1 = "hi Alice"
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"

corpus = [s1, s2, s3, s4, s5]

all_words = list(set([item for x in corpus for item in x.split()]))

v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
v4 = [1 if x in s4 else 0 for x in all_words]
v5 = [1 if x in s5 else 0 for x in all_words]

print(all_words)

print([v1, v2, v3, v4, v5])

['Claude', 'hello', 'Bob', 'hi', 'Alice', 'my', 'is', 'name']
[[0, 0, 0, 1, 1, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 0, 1, 1, 1], [1, 0, 0, 1, 1, 1, 1, 1], [0, 1, 1, 0, 0, 0, 0, 0]]


e) How many rows and columns does this matrix have?

In [28]:
s1 = "hi Alice"
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"
corpus = [s1, s2, s3, s4, s5]
all_words = list(set([item for x in corpus for item in x.split()]))

v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
v4 = [1 if x in s4 else 0 for x in all_words]
v5 = [1 if x in s5 else 0 for x in all_words]

matrix = [v1, v2, v3, v4, v5]

print("rows: " + str(len(matrix)))
print("columns: " + str(len(matrix[0])))

rows: 5
columns: 8


f) When using the Manhattan distance, which two sentences are the most similar?

In [35]:
def minkowski(x, y):
    if len(x) != len(y):
        raise RuntimeError("x and y must be the same direction")
    return sum([abs(x[i] - y[i])**1 for i in range(len(x))])**(1)

print(minkowski(v1, v2))
print(minkowski(v1, v3))
print(minkowski(v1, v4))
print(minkowski(v1, v5))
print(minkowski(v2, v3))
print(minkowski(v2, v4))
print(minkowski(v2, v5)) #this is the most similar
print(minkowski(v3, v4))
print(minkowski(v3, v5))
print(minkowski(v4, v5))

print("s2 and s5 are the most similar")





4
7
4
4
5
6
2
3
5
8
s2 and s5 are the most similar


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [37]:
import numpy as np

def pairwise(graphs, p):
    n = len(graphs)  
    distance_matrix = np.zeros((n, n)) 
    flattened_graphs = [g.flatten() for g in graphs]
    print(flattened_graphs)
    for i in range(n):
        for j in range(i + 1, n): 
            distance = np.sum(np.abs(flattened_graphs[i] - flattened_graphs[j])**p)**(1/p)
            distance_matrix[i, j] = distance_matrix[j, i] = distance  
    return distance_matrix

graph_1 = np.array([[1, 0, 0],  
                    [0, 0, 0],
                    [0, 0, 0]])

graph_2 = np.array([[1, 0, 0],  
                    [0, 0, 0],
                    [0, 0, 0]])

graph_3 = np.array([[1, 0, 0],  
                    [0, 0, 0],
                    [0, 0, 0]])

graphs = [graph_1, graph_2, graph_3]

print(pairwise(graphs, 2))

[array([1, 0, 0, 0, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 0, 0, 0, 0])]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
